"""Generate the quiz-bank migration from the question files in this folder.

Usage: python supabase/quiz-bank/build.py
Writes supabase/migrations/20261004200000_quiz_bank.sql (schema + seed).
"""

import json
from pathlib import Path

from rag import BANK

HERE = Path(__file__).parent
OUT = HERE.parent / "migrations" / "20261004200000_quiz_bank.sql"

SCHEMA = r"""-- Free quizzes from a pre-written question bank (replaces the Claude-powered Edge Function).
-- start_quiz() picks up to 5 random questions for an item, shuffles their options, and stores the
-- answer key in quiz_keys; submit_quiz() (earlier migration) grades against it. Nothing calls a paid API.
-- Generated by supabase/quiz-bank/build.py; edit the question files there, not this SQL.

create table if not exists public.quiz_bank (
  id            uuid primary key default gen_random_uuid(),
  item_id       text not null check (item_id ~ '^[a-z0-9]{1,8}-[0-9]{1,3}$'),
  question      text not null,
  options       jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  answer_index  int not null check (answer_index between 0 and 3),
  explanation   text not null
);

create index if not exists quiz_bank_item_idx on public.quiz_bank (item_id);

alter table public.quiz_bank enable row level security;  -- no policies: read only through start_quiz()
revoke all on public.quiz_bank from anon, authenticated;

-- Which roadmap items have quizzes, and how many questions each.
create or replace function public.quiz_items()
returns table (item_id text, questions int)
language sql
stable
security definer
set search_path = ''
as $$
  select b.item_id, count(*)::int from public.quiz_bank b group by b.item_id;
$$;

grant execute on function public.quiz_items() to anon, authenticated;

create or replace function public.start_quiz(p_item text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  recent int;
  attempt uuid;
  q record;
  opts jsonb;
  perm bigint[];
  qs jsonb := '[]'::jsonb;
  keys jsonb := '[]'::jsonb;
  expl jsonb := '[]'::jsonb;
begin
  if uid is null or not exists (select 1 from public.profiles p where p.id = uid and p.is_member) then
    raise exception 'Only lab members can take quizzes';
  end if;

  select count(*) into recent from public.quiz_attempts
   where user_id = uid and created_at > now() - interval '24 hours';
  if recent >= 50 then
    raise exception 'You have taken 50 quizzes in 24 hours. Take a break and try again tomorrow.';
  end if;

  for q in select * from public.quiz_bank where item_id = p_item order by random() limit 5 loop
    -- Shuffle the options so answer positions differ between attempts.
    select jsonb_agg(o.value order by o.r), array_agg(o.idx order by o.r)
      into opts, perm
      from (select value, ordinality - 1 as idx, random() as r
              from jsonb_array_elements(q.options) with ordinality) o;
    qs := qs || jsonb_build_array(jsonb_build_object('question', q.question, 'options', opts));
    keys := keys || to_jsonb(array_position(perm, q.answer_index::bigint) - 1);
    expl := expl || to_jsonb(q.explanation);
  end loop;

  if jsonb_array_length(qs) = 0 then
    raise exception 'There is no quiz for this item yet';
  end if;

  insert into public.quiz_attempts (user_id, item_id, questions, total, status)
  values (uid, p_item, qs, jsonb_array_length(qs), 'ready')
  returning id into attempt;

  insert into public.quiz_keys (attempt_id, answer_indexes, explanations)
  values (attempt, keys, expl);

  return jsonb_build_object('id', attempt, 'questions', qs);
end;
$$;

revoke all on function public.start_quiz(text) from public, anon;
grant execute on function public.start_quiz(text) to authenticated;

-- Seed (idempotent: replaces the bank for the items below).
"""


def sql_text(s: str) -> str:
    if "$q$" in s:
        raise ValueError(f"Text contains the quote delimiter: {s!r}")
    return f"$q${s}$q$"


def build() -> str:
    rows = []
    for item_id, questions in BANK.items():
        n = int(item_id.split("-")[1])
        for i, (question, correct, wrong, explanation) in enumerate(questions):
            if len(wrong) != 3 or correct in wrong:
                raise ValueError(f"{item_id} #{i + 1}: need one correct and three distinct wrong answers")
            pos = (i + n) % 4  # spread correct answers over positions even before shuffling
            options = wrong[:pos] + [correct] + wrong[pos:]
            rows.append(
                f"  ({sql_text(item_id)}, {sql_text(question)}, {sql_text(json.dumps(options, ensure_ascii=False))}::jsonb, "
                f"{pos}, {sql_text(explanation)})"
            )
    items = ", ".join(sql_text(k) for k in BANK)
    return (
        SCHEMA
        + f"delete from public.quiz_bank where item_id in ({items});\n\n"
        + "insert into public.quiz_bank (item_id, question, options, answer_index, explanation) values\n"
        + ",\n".join(rows)
        + ";\n"
    )


if __name__ == "__main__":
    sql = build()
    OUT.write_text(sql, encoding="utf-8")
    total = sum(len(v) for v in BANK.values())
    print(f"Wrote {OUT.name}: {total} questions for {len(BANK)} items")
