"""Question bank for the RAG course track (Harish Neel, Complete RAG Tutorial 2026).

Each entry: (question, correct answer, [three wrong answers], explanation).
Run `python supabase/quiz-bank/build.py` to regenerate the SQL seed after editing.
Questions test the concepts each video covers, not exact wording from the videos.
"""

BANK = {
    "rag-1": [
        ("What problem does RAG mainly solve?",
         "Letting an LLM answer with information it wasn't trained on",
         ["Making models train faster", "Shrinking the model so it runs on a phone", "Replacing prompts with code"],
         "RAG fetches relevant documents at question time and puts them in the prompt, so the model can use private or recent information."),
        ("What does RAG stand for?",
         "Retrieval-Augmented Generation",
         ["Recursive Answer Generation", "Ranked Attention Graph", "Reinforced Agent Generation"],
         "The model's generation is augmented with text retrieved from your own documents."),
        ("Without RAG, why might an LLM answer wrongly about your company's internal policies?",
         "It never saw those documents, so it may guess and hallucinate",
         ["LLMs can't read policy documents", "The temperature is always too high", "Policies are too short to answer from"],
         "A model only knows its training data; for unseen private documents it fills gaps with plausible-sounding guesses."),
        ("Which step happens at query time in a RAG system?",
         "Embedding the user's question and searching for similar chunks",
         ["Splitting all documents into chunks", "Training the embedding model", "Building the vector database from scratch"],
         "Chunking and indexing happen ahead of time; at query time you only embed the question and search."),
        ("What is the main advantage of RAG over fine-tuning for adding new facts?",
         "Updating knowledge means updating documents, not retraining the model",
         ["It permanently changes the model's weights", "It needs no data at all", "It makes the model smaller"],
         "Swapping a document in the index is instant and cheap; fine-tuning bakes facts into weights and has to be redone."),
        ("What is an LLM's knowledge cutoff?",
         "The date after which the model has no training data",
         ["The maximum length of a prompt", "The number of documents it can retrieve", "The point where the model stops generating"],
         "Anything that happened after the cutoff is unknown to the model unless you provide it, for example through RAG."),
        ("Which two stages make up a RAG system?",
         "Retrieval and generation",
         ["Tokenization and detokenization", "Training and evaluation", "Compression and decompression"],
         "First retrieve relevant text, then generate an answer from it."),
        ("A RAG app answers confidently but its cited chunks are unrelated to the question. What is the most likely weak point?",
         "The retrieval step returned irrelevant chunks",
         ["The GPU is too slow", "The question was too short to embed", "LLMs cannot cite sources"],
         "If the context is wrong, the generator has nothing correct to ground its answer in."),
    ],
    "rag-2": [
        ("What is a vector embedding?",
         "A list of numbers that represents the meaning of a piece of text",
         ["A compressed zip of a document", "A keyword index of the text", "An encrypted copy of the text"],
         "Embedding models map text to points in a high-dimensional space where similar meanings land close together."),
        ("Two sentences mean the same thing but use different words. Their embeddings should be:",
         "Close together in vector space",
         ["Identical bit for bit", "Far apart", "Of different lengths"],
         "Embeddings capture meaning, so paraphrases end up near each other even without shared words."),
        ("What does a vector database mainly do?",
         "Store embeddings and quickly find the ones nearest to a query vector",
         ["Train LLMs", "Convert PDFs to text", "Write the final answer"],
         "Vector databases are built for fast nearest-neighbour search over many vectors."),
        ("Which of these belongs to the ingestion (indexing) pipeline?",
         "Loading documents, chunking, embedding and storing them",
         ["Generating the final answer", "Rewriting the user's question", "Showing citations to the user"],
         "Ingestion prepares your documents once; the other steps run per question."),
        ("Why must documents and queries be embedded with the same model?",
         "Different models put vectors in different spaces, so distances between them mean nothing",
         ["It is a legal requirement", "Otherwise the text can't be tokenized", "It makes chunks shorter"],
         "Similarity only makes sense when both vectors come from the same embedding space."),
        ("An embedding model outputs 1536-dimensional vectors. What does that mean?",
         "Each text becomes a list of 1536 numbers",
         ["The model can read at most 1536 words", "There are 1536 documents", "The database has 1536 rows"],
         "Dimension is the length of each vector, not a limit on input or data size."),
        ("Searching by meaning rather than by exact words is called:",
         "Semantic search",
         ["Keyword search", "Regex search", "Boolean search"],
         "Semantic search compares embeddings, so it finds matches that share meaning but not wording."),
        ("Where does the LLM come in a basic RAG architecture?",
         "After retrieval, to write an answer from the retrieved chunks",
         ["Only during ingestion", "Before embedding, to tokenize documents", "It isn't used at all"],
         "Retrieval finds the context; the LLM turns that context plus the question into an answer."),
    ],
    "rag-3": [
        ("What does a document loader do?",
         "Reads files such as PDFs, text or web pages into text the pipeline can process",
         ["Embeds text into vectors", "Answers questions", "Ranks chunks by relevance"],
         "Loaders are the entry point of ingestion: they turn raw files into documents with text and metadata."),
        ("Why split documents into chunks before embedding?",
         "Models have size limits, and smaller pieces give more precise matches",
         ["To encrypt the documents", "Because vector databases only store single words", "To remove stop words"],
         "A focused chunk produces a focused embedding and fits comfortably into the prompt."),
        ("What is chunk overlap?",
         "Repeating some text from the end of one chunk at the start of the next",
         ["Storing each chunk twice", "Merging two documents into one", "Overlapping two embeddings"],
         "Overlap keeps a little shared context between neighbouring chunks."),
        ("Why use chunk overlap?",
         "So an idea cut at a chunk boundary still appears whole in at least one chunk",
         ["To make the database bigger on purpose", "To speed up embedding", "To avoid needing metadata"],
         "Without overlap, a sentence split across two chunks may not match well in either."),
        ("Chunks that are too large tend to:",
         "Mix several topics, so their embedding is less precise",
         ["Always improve answers", "Be impossible to store", "Lose all their metadata"],
         "One vector has to represent everything in the chunk; more topics means a blurrier vector."),
        ("Chunks that are too small tend to:",
         "Lose the surrounding context needed to answer",
         ["Always give better answers because they are cheaper", "Break the embedding model", "Ignore the question"],
         "A single sentence may match the query but miss the details around it."),
        ("What is usually stored alongside each chunk's vector?",
         "The chunk text and metadata such as the source file",
         ["Nothing else", "A copy of the LLM", "The user's password"],
         "You need the text to put in the prompt and the metadata to cite and filter."),
        ("In the course, Chroma is:",
         "An open-source vector database",
         ["An embedding model", "A PDF loader", "A chat interface"],
         "Chroma stores the chunk embeddings and runs the similarity search."),
    ],
    "rag-4": [
        ("What is a LangChain retriever's job?",
         "Take a query and return relevant documents",
         ["Generate the final answer", "Train the embedding model", "Split text into chunks"],
         "Retrievers are the search component; generation is a separate step."),
        ("In similarity search, k = 3 means:",
         "Return the 3 most similar chunks",
         ["Use 3 embedding models", "Split each document into 3 chunks", "Retry the search 3 times"],
         "k is how many top results come back."),
        ("What does a similarity score threshold do?",
         "Only returns chunks whose similarity is above a chosen value",
         ["Always returns exactly one chunk", "Sorts results alphabetically", "Removes duplicate documents"],
         "It filters out weak matches instead of always returning a fixed number."),
        ("What is the risk of setting k very high?",
         "Irrelevant chunks get into the prompt, confusing the model and costing more tokens",
         ["Retrieval becomes exact", "The embeddings change", "Nothing, more is always better"],
         "Extra low-quality context dilutes the useful part and increases cost."),
        ("What is the risk of a very strict score threshold?",
         "Some questions return no chunks at all",
         ["Too many chunks are returned", "Answers get longer", "The database gets corrupted"],
         "If nothing clears the bar, the model has no context to answer from."),
        ("Before searching, the retriever turns the user's question into:",
         "An embedding made with the same model used for the documents",
         ["A SQL query", "A list of keywords only", "An image"],
         "The question vector is compared with the stored chunk vectors."),
        ("Why return chunk metadata with search results?",
         "So the answer can cite which document it came from",
         ["It is required to compute similarity", "To make the prompt longer", "To train the model"],
         "Metadata like the source file lets users check where an answer came from."),
        ("Retrieval returns the right chunks, but the answer is still wrong. Where is the problem most likely?",
         "In the generation step: the prompt or the model",
         ["In the document loader", "In the database's tokenizer", "In cosine similarity"],
         "If the right context arrived, the failure is in how the model was asked to use it."),
    ],
    "rag-5": [
        ("What does cosine similarity measure?",
         "The angle between two vectors, meaning how aligned they are",
         ["The exact difference in their lengths", "The number of shared words", "How much memory they use"],
         "Cosine looks at direction; vectors pointing the same way are similar."),
        ("What is the cosine similarity of two vectors pointing in exactly the same direction?",
         "1",
         ["0", "-1", "Infinity"],
         "cos(0°) = 1, the maximum similarity."),
        ("What is the cosine similarity of two perpendicular (orthogonal) vectors?",
         "0",
         ["1", "-1", "0.5"],
         "cos(90°) = 0: the vectors share no direction."),
        ("Which is the cosine similarity formula?",
         "dot(A, B) / (|A| x |B|)",
         ["|A| + |B|", "dot(A, B) x |A|", "|A - B| squared"],
         "The dot product divided by both lengths gives the cosine of the angle."),
        ("If both vectors are normalised to length 1, cosine similarity equals:",
         "Their dot product",
         ["Zero", "Their sum", "Their Euclidean distance"],
         "With |A| = |B| = 1 the denominator is 1, leaving just the dot product."),
        ("Why is cosine often preferred over the raw dot product for text embeddings?",
         "It ignores vector length and focuses on direction, which carries the meaning",
         ["It is always faster to compute", "It works without embeddings", "It always returns whole numbers"],
         "Length can vary with things like text length; direction is the more reliable signal of meaning."),
        ("What is the range of cosine similarity?",
         "-1 to 1",
         ["0 to 100", "0 to infinity", "-100 to 100"],
         "It is the cosine of an angle, so it is bounded by -1 and 1."),
        ("A query scores 0.82 against chunk A and 0.35 against chunk B. Which chunk is more relevant?",
         "Chunk A",
         ["Chunk B", "They are equally relevant", "Cosine scores can't be compared"],
         "Higher cosine similarity means the vectors point in more similar directions."),
    ],
    "rag-6": [
        ("How do retrieved chunks reach the LLM?",
         "They are inserted into the prompt as context along with the question",
         ["They are fine-tuned into the model's weights", "They are sent to a separate model", "They are stored in the model's memory permanently"],
         "RAG is prompt construction: context plus question, sent in one request."),
        ("Which instruction best reduces hallucination in a RAG prompt?",
         "Answer only from the provided context, and say you don't know if it isn't there",
         ["Be creative and fill any gaps", "Ignore the context if you are unsure", "Always give a long, detailed answer"],
         "Telling the model to stay inside the context and admit gaps keeps answers grounded."),
        ("Why should a RAG app be allowed to say \"I don't know\"?",
         "It is better than inventing an answer the documents don't support",
         ["It saves GPU time", "Vector databases require it", "It makes retrieval faster"],
         "A wrong confident answer does more harm than an honest gap."),
        ("What is the correct order of a basic RAG request?",
         "Embed question, retrieve chunks, build prompt, generate answer",
         ["Generate answer, retrieve chunks, embed question, build prompt", "Build prompt, embed documents, train model, answer", "Retrieve chunks, embed question, chunk documents, answer"],
         "Each step needs the output of the previous one."),
        ("What does it mean to ground an answer?",
         "Base it on retrieved source text that can be checked",
         ["Run it on a server", "Make it shorter", "Translate it"],
         "Grounded answers can be traced back to specific passages."),
        ("Putting 20 long chunks into every prompt mainly:",
         "Raises cost and latency and can bury the relevant part",
         ["Always improves accuracy", "Has no effect", "Reduces token usage"],
         "More context isn't free; the model may also overlook the one passage that matters."),
        ("Why show sources or citations with answers?",
         "Users can verify the answer and spot hallucinations",
         ["Embeddings require it", "It makes the model faster", "It reduces chunk size"],
         "Citations make the system checkable and build trust."),
        ("A user asks something your documents don't cover. What should a good RAG app do?",
         "Say the documents don't cover it",
         ["Make up a plausible answer", "Return a random chunk", "Crash with an error"],
         "Admitting the gap is the grounded behaviour."),
    ],
    "rag-7": [
        ("In a naive RAG chat, why does the follow-up \"What about its price?\" fail?",
         "\"Its\" means nothing on its own, so retrieval searches for the wrong thing",
         ["Prices can't be embedded", "Follow-up questions are too long", "The LLM forgets English"],
         "Without the earlier messages the question has no subject to search for."),
        ("What does a history-aware retriever do?",
         "Rewrites the latest question into a standalone question using the chat history, then searches",
         ["Deletes the chat history", "Stores every answer in the vector database", "Ignores the user's question"],
         "The rewritten question carries the missing context into the search."),
        ("Where is chat history used in conversational RAG?",
         "To reformulate the query and as context when answering",
         ["Only to train the model", "Nowhere", "Only inside the vector database"],
         "History helps both retrieval (rewriting) and generation (continuity)."),
        ("What is the risk of sending the entire chat history with every request?",
         "Cost and context usage grow with every turn",
         ["Embeddings become negative", "Retrieval becomes exact", "There is no risk"],
         "Long histories eat context window and tokens; trimming or summarising helps."),
        ("What is a standalone question?",
         "One that can be understood without the previous messages",
         ["A question with one word", "A question asked only once", "A question without punctuation"],
         "\"What is the Model Y's price?\" is standalone; \"What about its price?\" is not."),
        ("How is chat history usually stored?",
         "As a list of user and assistant messages",
         ["As a single embedding", "As a PDF", "Inside the vector index"],
         "Message lists are what chat models take as input."),
        ("Why not embed the whole conversation as the search query?",
         "Older topics in the history dilute the search for the current question",
         ["It isn't allowed", "Embeddings can't contain questions", "It would always be better"],
         "A focused standalone question retrieves better than a mix of everything said so far."),
        ("Which component usually rewrites the follow-up question?",
         "An LLM call with a rewrite prompt",
         ["The vector database", "The text splitter", "The document loader"],
         "Rewriting needs language understanding, so it is an LLM step."),
    ],
    "rag-8": [
        ("How does fixed-size chunking split text?",
         "By a set number of characters or tokens",
         ["By meaning", "By headings only", "At random points"],
         "It is the simplest strategy: cut every N characters or tokens."),
        ("What is the main weakness of fixed-size chunking?",
         "It can cut sentences or ideas in half",
         ["It is too slow", "Its chunks can't be embedded", "It needs an LLM"],
         "Cuts ignore the structure of the text."),
        ("What does recursive splitting try to do?",
         "Split on natural boundaries (paragraphs, then lines, then sentences) and go smaller only when needed",
         ["Split at random", "Merge documents together", "Remove punctuation"],
         "It respects structure first and only falls back to finer cuts for oversized pieces."),
        ("Semantic chunking decides chunk boundaries using:",
         "Changes in meaning measured with embeddings",
         ["File size", "The number of images", "Alphabetical order"],
         "When neighbouring sentences drift apart in meaning, a new chunk starts."),
        ("What is the typical trade-off of larger chunks?",
         "More context per chunk but less precise retrieval",
         ["They are always better", "They are always worse", "Chunk size has no effect"],
         "Big chunks carry more context but their embeddings are less specific."),
        ("What does an overlap of about 10-20% usually give you?",
         "Context kept across boundaries at a small storage cost",
         ["Double the storage", "Broken retrieval", "Fewer duplicates"],
         "A modest overlap protects boundary sentences without bloating the index much."),
        ("For an FAQ where each question and answer is self-contained, what is the best chunk?",
         "One question with its answer",
         ["Every 50 characters", "The whole document as one chunk", "Every single word"],
         "Matching the chunk to the natural unit of meaning gives the cleanest retrieval."),
        ("Why test chunking settings with real questions?",
         "The best settings depend on your documents and your queries",
         ["Chunking has no effect on results", "LangChain requires it", "To train the embedding model"],
         "There is no universal best chunk size; measure on your own data."),
    ],
    "rag-9": [
        ("In what order does RecursiveCharacterTextSplitter try separators by default?",
         "Paragraph breaks, then line breaks, then spaces, then single characters",
         ["Single characters first, then words", "Sentences found by regex only", "Headings, then tables, then images"],
         "The defaults are \"\\n\\n\", \"\\n\", \" \" and \"\": coarse to fine."),
        ("Why split by tokens instead of characters?",
         "Model limits and costs are measured in tokens",
         ["Tokens are always whole words", "Characters can't be embedded", "PDFs require it"],
         "Token-based sizes map directly onto context windows and pricing."),
        ("What can a Markdown header splitter do?",
         "Split on headings and keep the heading as metadata",
         ["Translate the Markdown", "Remove all code blocks", "Render it as HTML"],
         "Headings become context for each chunk, which helps retrieval and citations."),
        ("Why use a language-aware splitter for source code?",
         "It splits on functions and classes instead of in the middle of a statement",
         ["It runs the code", "It removes comments", "It compresses the code"],
         "Code has its own structure; respecting it keeps chunks meaningful."),
        ("What does chunk_size=500, chunk_overlap=50 mean?",
         "Chunks of up to about 500 units, with 50 shared between neighbours",
         ["500 chunks of 50 words each", "50 chunks of 500 words each", "An overlap of 500 units"],
         "Size is the maximum per chunk; overlap is how much repeats between neighbours."),
        ("Why might a splitter produce a chunk smaller than chunk_size?",
         "It stopped at a natural separator rather than cutting mid-text",
         ["It's a bug", "The overlap was negative", "The embeddings shrank"],
         "chunk_size is a maximum, not an exact target."),
        ("What goes wrong if a table is split row by row without its header?",
         "The chunks lose the column names needed to understand them",
         ["Nothing, it's perfect", "Embeddings get faster", "The table gets more accurate"],
         "A row of numbers without headers has no meaning on its own."),
        ("What does length_function control in a text splitter?",
         "How chunk size is measured, for example characters or tokens",
         ["How many chunks are returned", "The embedding dimension", "The LLM's temperature"],
         "Swap in a token counter to make chunk_size mean tokens."),
    ],
    "rag-10": [
        ("When does a semantic chunker start a new chunk?",
         "When the embedding distance between consecutive sentences jumps above a threshold",
         ["After a fixed number of characters", "Whenever a heading appears", "At random"],
         "A large jump in distance signals a change of topic."),
        ("A percentile breakpoint threshold of 95 means:",
         "Split only at the largest 5% of distance jumps",
         ["Make 95 chunks", "Use 95% overlap", "Cut every 95 characters"],
         "Only the biggest topic shifts become chunk boundaries."),
        ("What extra cost does semantic chunking have compared with recursive splitting?",
         "Every sentence has to be embedded during ingestion",
         ["It needs GPUs at query time", "Answers get longer", "There is no extra cost"],
         "It needs embeddings just to decide where to cut."),
        ("When is semantic chunking most useful?",
         "For long text that drifts between topics without clear headings",
         ["For short tweets", "For tables", "For source code"],
         "Without structural markers, meaning is the best guide to boundaries."),
        ("What is a downside of semantic chunking?",
         "Chunk sizes can vary a lot, some very large or very small",
         ["Its chunks can't be stored", "It always needs internet access", "It breaks cosine similarity"],
         "Boundaries follow meaning, not size, so sizes are uneven."),
        ("What does a semantic chunker compare?",
         "Neighbouring sentences (or small groups of sentences) with each other",
         ["Each sentence with the user's query", "Whole documents with each other", "Words with letters"],
         "It measures how much meaning shifts from one sentence to the next."),
        ("Lowering the breakpoint threshold generally gives:",
         "More, smaller chunks",
         ["Fewer, larger chunks", "Exactly the same chunks", "No chunks at all"],
         "A lower bar means more distance jumps count as boundaries."),
        ("Does semantic chunking change how retrieval works at query time?",
         "No, it only changes how documents are split during ingestion",
         ["Yes, it needs a new kind of database", "Yes, it calls an LLM for every query", "Yes, it doubles query cost"],
         "The resulting chunks are embedded and searched like any others."),
    ],
    "rag-11": [
        ("What does agentic chunking use to decide chunk boundaries?",
         "An LLM that reads the text",
         ["Regular expressions", "A fixed size", "Cosine similarity only"],
         "The model groups text into chunks based on its understanding of the content."),
        ("In agentic chunking, what is a proposition?",
         "A short, self-contained statement of a single fact",
         ["A full paragraph", "A heading", "An embedding vector"],
         "Propositions are small, atomic facts that make sense on their own."),
        ("What is the main cost of agentic chunking?",
         "LLM calls over all the text during ingestion, which is slower and more expensive",
         ["There is no extra cost", "Smaller vectors", "Faster queries"],
         "Every document passes through a model before it is indexed."),
        ("Why rewrite \"He founded it in 2002\" as \"Elon Musk founded SpaceX in 2002\"?",
         "So the chunk makes sense on its own when retrieved",
         ["To make it shorter", "Because Chroma requires it", "To remove the names"],
         "Retrieved chunks arrive without their neighbours, so pronouns must be resolved."),
        ("When is agentic chunking worth the cost?",
         "For high-value documents where retrieval quality matters more than ingestion cost",
         ["For every tweet", "For real-time log streams", "Never"],
         "Pay the extra cost once where answer quality really matters."),
        ("What is a risk of agentic chunking?",
         "The LLM may drop or change facts while rewriting",
         ["Its chunks can't be embedded", "It is fully deterministic", "Its chunks are too small to store"],
         "Any rewriting step can introduce errors; spot-check the output."),
        ("When does agentic chunking run?",
         "During ingestion, once per document",
         ["On every user question", "Only while training the model", "Never"],
         "Like other chunking, it is part of preparing the index."),
        ("How does agentic chunking differ from semantic chunking?",
         "It relies on an LLM's understanding instead of embedding distances",
         ["They are identical", "It uses no model at all", "It only works on code"],
         "Semantic chunking measures distances; agentic chunking asks a model to decide."),
    ],
    "rag-12": [
        ("What is the problem with images in PDFs for a text-only RAG pipeline?",
         "Information in charts and images is lost if you only extract the text",
         ["Images are encrypted", "Text can't be extracted from PDFs", "There is no problem"],
         "A chart's numbers never reach the index unless you handle the image."),
        ("What is a common way to make images searchable?",
         "Generate text summaries of the images with a vision model and embed the summaries",
         ["Delete the images", "Embed the image file size", "Only index the PDF title"],
         "Summaries turn visual content into text the retriever can match."),
        ("How does the unstructured library help?",
         "It partitions documents into elements such as titles, text, tables and images",
         ["It trains models", "It hosts the vector database", "It provides a chat interface"],
         "Knowing each element's type lets you treat tables and images differently."),
        ("Why keep a link from an image summary back to the original image?",
         "So the answer step can show the real image or pass it to a vision model",
         ["Cosine similarity needs it", "It reduces cost", "There is no reason"],
         "The summary is for search; the image itself may be needed to answer."),
        ("How should tables usually be handled?",
         "Kept intact, for example as HTML or Markdown, rather than split mid-table",
         ["Split into single cells", "Removed", "Converted into images"],
         "A table only makes sense with its rows and headers together."),
        ("What can a multimodal embedding model do?",
         "Put images and text in the same vector space, so text queries can match images",
         ["Embed only text", "Embed only audio", "Compress PDFs"],
         "A shared space makes cross-modal search possible."),
        ("What extra cost does multimodal RAG usually add?",
         "Vision-model calls during ingestion to describe images",
         ["Nothing", "A smaller database", "Faster answers"],
         "Each image needs processing before it can be indexed."),
        ("What does a scanned, image-only PDF need first?",
         "OCR to extract the text",
         ["Nothing", "Cosine similarity", "Bigger chunks"],
         "Without OCR there is no text to chunk or embed."),
    ],
    "rag-13": [
        ("What does Maximal Marginal Relevance (MMR) aim for?",
         "Results that are relevant but also different from each other",
         ["Only the single most similar results", "Random results", "The shortest chunks"],
         "MMR balances relevance against redundancy."),
        ("Why does diversity in results matter?",
         "The top results can be near-duplicates that waste context",
         ["It doesn't matter", "To use more tokens on purpose", "Cosine similarity requires it"],
         "Three copies of the same paragraph add no new information."),
        ("In MMR, lambda_mult = 1 means:",
         "Pure relevance, with no diversity",
         ["Pure diversity", "Random selection", "No results"],
         "Lower values push harder toward diverse results."),
        ("What does metadata filtering do?",
         "Restricts the search to chunks whose metadata matches, for example source = \"Tesla\"",
         ["Changes the embeddings", "Deletes the metadata", "Sorts results alphabetically"],
         "Filters apply hard conditions before or alongside similarity search."),
        ("For \"What did Nvidia's report say about revenue?\", what is the best use of metadata?",
         "Filter to chunks from the Nvidia document before the similarity search",
         ["Ignore metadata", "Filter by chunk length", "Pick a random document"],
         "This keeps other companies' revenue sections out of the results."),
        ("In MMR, what is fetch_k?",
         "How many candidates are fetched before MMR picks the final k",
         ["The final number of results", "The embedding dimension", "The chunk overlap"],
         "MMR needs a larger pool to choose a diverse subset from."),
        ("What does score-threshold retrieval return?",
         "All chunks above a similarity cutoff, possibly none",
         ["Always exactly k chunks", "Exactly one chunk", "Random chunks"],
         "The number of results depends on how many clear the bar."),
        ("Why combine metadata filters with similarity search?",
         "Filters enforce hard rules while similarity ranks by meaning",
         ["They do the same thing", "Filters are always slower", "Similarity can't rank results"],
         "Together they give results that are both allowed and relevant."),
    ],
    "rag-14": [
        ("What is multi-query retrieval?",
         "Using an LLM to write several versions of the question and retrieving for each",
         ["Asking the user to rephrase", "Querying several databases with the same text", "Repeating the same query"],
         "Different phrasings reach different parts of the vector space."),
        ("Why does multi-query retrieval help?",
         "One phrasing can miss chunks that another phrasing finds, so recall improves",
         ["It is faster", "It uses fewer tokens", "It only improves precision"],
         "Covering more phrasings means fewer relevant chunks are missed."),
        ("After retrieving for each variation, what happens to the results?",
         "They are merged and de-duplicated",
         ["All but the first list are discarded", "They are averaged into one vector", "They are sorted alphabetically"],
         "The union of all lists, without repeats, goes forward."),
        ("What is the main cost of multi-query retrieval?",
         "An extra LLM call plus several searches per question",
         ["There is no cost", "Bigger embeddings", "Retraining the model"],
         "You pay for generating the variations and running each search."),
        ("What does recall mean in retrieval?",
         "The share of relevant chunks that you actually retrieved",
         ["How fast retrieval is", "How much memory it uses", "The share of retrieved chunks that are relevant"],
         "The last option describes precision; recall is about not missing relevant chunks."),
        ("When is multi-query retrieval a good fit?",
         "For vague or short questions that could be phrased many ways",
         ["Exact ID lookups", "Single-keyword searches", "When there are no documents"],
         "Ambiguous questions benefit most from multiple phrasings."),
        ("Multi-query can be combined with reciprocal rank fusion to:",
         "Rank the merged results by how high they appear across the lists",
         ["Only delete duplicates", "Change the embeddings", "Do nothing useful"],
         "Chunks that rank well for several phrasings rise to the top."),
        ("What is a risk of multi-query retrieval?",
         "Generated variations can drift from the user's intent and pull in off-topic chunks",
         ["There is no risk", "Recall goes down", "Results can't be merged"],
         "A bad rewrite searches for something the user didn't ask."),
    ],
    "rag-15": [
        ("What does reciprocal rank fusion (RRF) combine?",
         "Several ranked result lists into one ranking",
         ["Several embeddings into one", "Several chunks into one", "Several models into one"],
         "It fuses rankings from different searches or retrievers."),
        ("What is the RRF score of a document?",
         "The sum over all lists of 1 / (k + rank)",
         ["rank x k", "cosine similarity x rank", "Its highest rank"],
         "Each list contributes more when the document ranks higher in it."),
        ("Why does RRF use ranks instead of raw scores?",
         "Scores from different retrievers (like BM25 and cosine) aren't on the same scale",
         ["Ranks are faster to compute", "Scores are kept secret", "There is no reason"],
         "Ranks are comparable across retrievers; raw scores are not."),
        ("Document X is ranked 1st in two lists; document Y is 1st in only one. After RRF:",
         "X gets the higher fused score",
         ["They get the same score", "Y gets the higher score", "It can't be determined"],
         "X collects a contribution from both lists."),
        ("What is a common value for the constant k in RRF?",
         "60",
         ["1", "1000", "0"],
         "k = 60 comes from the original RRF paper and is a widely used default."),
        ("What does a larger k do in RRF?",
         "Shrinks the gap between top ranks, so lower-ranked items matter relatively more",
         ["Nothing", "Removes documents", "Reverses the ranking"],
         "With a large k, 1/(k+1) and 1/(k+10) are closer together."),
        ("A document appears in only one list, at rank 50, with k = 60. What does it contribute?",
         "1/110",
         ["50/60", "60/50", "110"],
         "1 / (60 + 50) = 1/110."),
        ("Where is RRF typically used?",
         "Fusing results from multi-query or hybrid (keyword plus vector) search",
         ["Chunking documents", "Creating embeddings", "Generating answers"],
         "Whenever several ranked lists need to become one, RRF is a simple choice."),
    ],
    "rag-16": [
        ("What is BM25?",
         "A keyword-based ranking function",
         ["An embedding model", "A vector database", "A large language model"],
         "BM25 scores documents by term frequency and rarity, without embeddings."),
        ("When does keyword search beat vector search?",
         "When exact terms matter, like product codes, names or error codes",
         ["When the query uses synonyms", "When the query is a paraphrase", "Never"],
         "Embeddings can blur exact strings; keyword search matches them precisely."),
        ("When does vector search beat keyword search?",
         "When the query uses different words with the same meaning",
         ["Exact ID lookups", "When there are no documents", "Never"],
         "Semantic matching finds paraphrases that share no keywords."),
        ("What is hybrid search?",
         "Running keyword and vector search and combining the results",
         ["Vector search only", "Keyword search run twice", "Letting the LLM pick documents"],
         "It gets the strengths of both approaches."),
        ("How do dense and sparse retrieval differ?",
         "Dense uses embeddings with mostly non-zero values; sparse uses keyword vectors that are mostly zeros",
         ["Dense is keyword-based and sparse uses embeddings", "They are the same thing", "Dense vectors are always shorter"],
         "Sparse vectors have one slot per vocabulary term, nearly all empty."),
        ("What do the weights in an EnsembleRetriever control?",
         "How much each retriever contributes to the final ranking",
         ["The embedding dimension", "The chunk size", "The LLM's temperature"],
         "For example 0.5/0.5 treats keyword and vector search equally."),
        ("For the query \"error E1042 in pump\", why lean more on keyword search?",
         "The exact code E1042 matters more than general meaning",
         ["Codes embed especially well", "The query is short", "No particular reason"],
         "Keyword search reliably matches the exact code."),
        ("What does BM25 need that vector search doesn't?",
         "Term statistics over the documents, such as word frequencies",
         ["A GPU", "An LLM", "Images"],
         "BM25 scores depend on how often terms appear in each document and across the collection."),
    ],
    "rag-17": [
        ("What does a reranker do?",
         "Re-scores a small set of retrieved candidates more accurately and reorders them",
         ["Replaces the vector database", "Splits documents into chunks", "Writes the final answer"],
         "Reranking is a precision step on top of a first-stage search."),
        ("What is two-stage retrieval?",
         "A fast, broad search for many candidates, then a slower, precise rerank of those",
         ["Using two vector databases", "Using two LLMs to answer", "Retrying a failed search"],
         "Stage one is cheap and wide; stage two is accurate and narrow."),
        ("How does a cross-encoder differ from a bi-encoder?",
         "A cross-encoder reads the query and document together; a bi-encoder embeds them separately",
         ["They are the same", "A cross-encoder is always faster", "A bi-encoder reads query and document together"],
         "Reading them together lets the model judge relevance more precisely."),
        ("Why not run a cross-encoder over every document?",
         "It is too slow and costly, since it runs once per query-document pair",
         ["It is less accurate", "It can't process text", "It is free, so there is no reason not to"],
         "That's why it's only applied to a short candidate list."),
        ("What is a typical reranking setup?",
         "Retrieve the top 20-50, rerank them, keep the top 3-5 for the prompt",
         ["Retrieve 1 and rerank it", "Rerank every document in the database", "Skip retrieval entirely"],
         "Wide first, then narrow to what the model actually needs."),
        ("What is Cohere Rerank?",
         "A hosted reranking API",
         ["A vector store", "A text splitter", "A chat model"],
         "You send a query and candidate texts; it returns relevance scores."),
        ("What does reranking mainly improve?",
         "The precision of the final chunks sent to the LLM",
         ["Ingestion speed", "Storage size", "The recall of the first-stage search"],
         "It can only reorder what stage one found, so it sharpens precision."),
        ("What is the trade-off of adding a reranker?",
         "Extra latency and cost on every query",
         ["There is none", "Lower accuracy", "Bigger chunks"],
         "Each question needs an additional model call."),
    ],
}
