import data from "./challenges.gen.json";

export type Level = "easy" | "medium" | "hard";

export interface ChallengeTest {
  readonly name: string;
  readonly code: string;
  readonly hidden: boolean;
}

export interface Challenge {
  readonly id: string;
  /** Roadmap item this challenge practises. */
  readonly item: string;
  readonly title: string;
  readonly level: Level;
  readonly xp: number;
  readonly prompt: string;
  readonly starter: string;
  readonly tests: readonly ChallengeTest[];
}

/** Generated by site/challenges/build.py (which also proves each reference solution passes). */
export const CHALLENGES: readonly Challenge[] = data as Challenge[];

export function findChallenge(id: string): Challenge | undefined {
  return CHALLENGES.find((c) => c.id === id);
}

export interface TestResult {
  readonly name: string;
  readonly ok: boolean;
  readonly message: string;
}

export interface RunResult {
  readonly error: string | null;
  readonly stdout: string;
  readonly results: readonly TestResult[];
}

export function allPassed(r: RunResult): boolean {
  return r.error === null && r.results.length > 0 && r.results.every((t) => t.ok);
}

/** What the in-browser Python runner is doing. */
export type RunnerState = "idle" | "loading" | "running";
