-- Free quizzes from a pre-written question bank (replaces the Claude-powered Edge Function).
-- start_quiz() picks up to 5 random questions for an item, shuffles their options, and stores the
-- answer key in quiz_keys; submit_quiz() (earlier migration) grades against it. Nothing calls a paid API.
-- Generated by supabase/quiz-bank/build.py; edit the question files there, not this SQL.

create table if not exists public.quiz_bank (
  id            uuid primary key default gen_random_uuid(),
  item_id       text not null check (item_id ~ '^[a-z0-9]{1,8}-[0-9]{1,3}$'),
  question      text not null,
  options       jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  answer_index  int not null check (answer_index between 0 and 3),
  explanation   text not null
);

create index if not exists quiz_bank_item_idx on public.quiz_bank (item_id);

alter table public.quiz_bank enable row level security;  -- no policies: read only through start_quiz()
revoke all on public.quiz_bank from anon, authenticated;

-- Which roadmap items have quizzes, and how many questions each.
create or replace function public.quiz_items()
returns table (item_id text, questions int)
language sql
stable
security definer
set search_path = ''
as $$
  select b.item_id, count(*)::int from public.quiz_bank b group by b.item_id;
$$;

grant execute on function public.quiz_items() to anon, authenticated;

create or replace function public.start_quiz(p_item text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  recent int;
  attempt uuid;
  q record;
  opts jsonb;
  perm bigint[];
  qs jsonb := '[]'::jsonb;
  keys jsonb := '[]'::jsonb;
  expl jsonb := '[]'::jsonb;
begin
  if uid is null or not exists (select 1 from public.profiles p where p.id = uid and p.is_member) then
    raise exception 'Only lab members can take quizzes';
  end if;

  select count(*) into recent from public.quiz_attempts
   where user_id = uid and created_at > now() - interval '24 hours';
  if recent >= 50 then
    raise exception 'You have taken 50 quizzes in 24 hours. Take a break and try again tomorrow.';
  end if;

  for q in select * from public.quiz_bank where item_id = p_item order by random() limit 5 loop
    -- Shuffle the options so answer positions differ between attempts.
    select jsonb_agg(o.value order by o.r), array_agg(o.idx order by o.r)
      into opts, perm
      from (select value, ordinality - 1 as idx, random() as r
              from jsonb_array_elements(q.options) with ordinality) o;
    qs := qs || jsonb_build_array(jsonb_build_object('question', q.question, 'options', opts));
    keys := keys || to_jsonb(array_position(perm, q.answer_index::bigint) - 1);
    expl := expl || to_jsonb(q.explanation);
  end loop;

  if jsonb_array_length(qs) = 0 then
    raise exception 'There is no quiz for this item yet';
  end if;

  insert into public.quiz_attempts (user_id, item_id, questions, total, status)
  values (uid, p_item, qs, jsonb_array_length(qs), 'ready')
  returning id into attempt;

  insert into public.quiz_keys (attempt_id, answer_indexes, explanations)
  values (attempt, keys, expl);

  return jsonb_build_object('id', attempt, 'questions', qs);
end;
$$;

revoke all on function public.start_quiz(text) from public, anon;
grant execute on function public.start_quiz(text) to authenticated;

-- Seed (idempotent: replaces the bank for the items below).
delete from public.quiz_bank where item_id in ($q$rag-1$q$, $q$rag-2$q$, $q$rag-3$q$, $q$rag-4$q$, $q$rag-5$q$, $q$rag-6$q$, $q$rag-7$q$, $q$rag-8$q$, $q$rag-9$q$, $q$rag-10$q$, $q$rag-11$q$, $q$rag-12$q$, $q$rag-13$q$, $q$rag-14$q$, $q$rag-15$q$, $q$rag-16$q$, $q$rag-17$q$);

insert into public.quiz_bank (item_id, question, options, answer_index, explanation) values
  ($q$rag-1$q$, $q$What problem does RAG mainly solve?$q$, $q$["Making models train faster", "Letting an LLM answer with information it wasn't trained on", "Shrinking the model so it runs on a phone", "Replacing prompts with code"]$q$::jsonb, 1, $q$RAG fetches relevant documents at question time and puts them in the prompt, so the model can use private or recent information.$q$),
  ($q$rag-1$q$, $q$What does RAG stand for?$q$, $q$["Recursive Answer Generation", "Ranked Attention Graph", "Retrieval-Augmented Generation", "Reinforced Agent Generation"]$q$::jsonb, 2, $q$The model's generation is augmented with text retrieved from your own documents.$q$),
  ($q$rag-1$q$, $q$Without RAG, why might an LLM answer wrongly about your company's internal policies?$q$, $q$["LLMs can't read policy documents", "The temperature is always too high", "Policies are too short to answer from", "It never saw those documents, so it may guess and hallucinate"]$q$::jsonb, 3, $q$A model only knows its training data; for unseen private documents it fills gaps with plausible-sounding guesses.$q$),
  ($q$rag-1$q$, $q$Which step happens at query time in a RAG system?$q$, $q$["Embedding the user's question and searching for similar chunks", "Splitting all documents into chunks", "Training the embedding model", "Building the vector database from scratch"]$q$::jsonb, 0, $q$Chunking and indexing happen ahead of time; at query time you only embed the question and search.$q$),
  ($q$rag-1$q$, $q$What is the main advantage of RAG over fine-tuning for adding new facts?$q$, $q$["It permanently changes the model's weights", "Updating knowledge means updating documents, not retraining the model", "It needs no data at all", "It makes the model smaller"]$q$::jsonb, 1, $q$Swapping a document in the index is instant and cheap; fine-tuning bakes facts into weights and has to be redone.$q$),
  ($q$rag-1$q$, $q$What is an LLM's knowledge cutoff?$q$, $q$["The maximum length of a prompt", "The number of documents it can retrieve", "The date after which the model has no training data", "The point where the model stops generating"]$q$::jsonb, 2, $q$Anything that happened after the cutoff is unknown to the model unless you provide it, for example through RAG.$q$),
  ($q$rag-1$q$, $q$Which two stages make up a RAG system?$q$, $q$["Tokenization and detokenization", "Training and evaluation", "Compression and decompression", "Retrieval and generation"]$q$::jsonb, 3, $q$First retrieve relevant text, then generate an answer from it.$q$),
  ($q$rag-1$q$, $q$A RAG app answers confidently but its cited chunks are unrelated to the question. What is the most likely weak point?$q$, $q$["The retrieval step returned irrelevant chunks", "The GPU is too slow", "The question was too short to embed", "LLMs cannot cite sources"]$q$::jsonb, 0, $q$If the context is wrong, the generator has nothing correct to ground its answer in.$q$),
  ($q$rag-2$q$, $q$What is a vector embedding?$q$, $q$["A compressed zip of a document", "A keyword index of the text", "A list of numbers that represents the meaning of a piece of text", "An encrypted copy of the text"]$q$::jsonb, 2, $q$Embedding models map text to points in a high-dimensional space where similar meanings land close together.$q$),
  ($q$rag-2$q$, $q$Two sentences mean the same thing but use different words. Their embeddings should be:$q$, $q$["Identical bit for bit", "Far apart", "Of different lengths", "Close together in vector space"]$q$::jsonb, 3, $q$Embeddings capture meaning, so paraphrases end up near each other even without shared words.$q$),
  ($q$rag-2$q$, $q$What does a vector database mainly do?$q$, $q$["Store embeddings and quickly find the ones nearest to a query vector", "Train LLMs", "Convert PDFs to text", "Write the final answer"]$q$::jsonb, 0, $q$Vector databases are built for fast nearest-neighbour search over many vectors.$q$),
  ($q$rag-2$q$, $q$Which of these belongs to the ingestion (indexing) pipeline?$q$, $q$["Generating the final answer", "Loading documents, chunking, embedding and storing them", "Rewriting the user's question", "Showing citations to the user"]$q$::jsonb, 1, $q$Ingestion prepares your documents once; the other steps run per question.$q$),
  ($q$rag-2$q$, $q$Why must documents and queries be embedded with the same model?$q$, $q$["It is a legal requirement", "Otherwise the text can't be tokenized", "Different models put vectors in different spaces, so distances between them mean nothing", "It makes chunks shorter"]$q$::jsonb, 2, $q$Similarity only makes sense when both vectors come from the same embedding space.$q$),
  ($q$rag-2$q$, $q$An embedding model outputs 1536-dimensional vectors. What does that mean?$q$, $q$["The model can read at most 1536 words", "There are 1536 documents", "The database has 1536 rows", "Each text becomes a list of 1536 numbers"]$q$::jsonb, 3, $q$Dimension is the length of each vector, not a limit on input or data size.$q$),
  ($q$rag-2$q$, $q$Searching by meaning rather than by exact words is called:$q$, $q$["Semantic search", "Keyword search", "Regex search", "Boolean search"]$q$::jsonb, 0, $q$Semantic search compares embeddings, so it finds matches that share meaning but not wording.$q$),
  ($q$rag-2$q$, $q$Where does the LLM come in a basic RAG architecture?$q$, $q$["Only during ingestion", "After retrieval, to write an answer from the retrieved chunks", "Before embedding, to tokenize documents", "It isn't used at all"]$q$::jsonb, 1, $q$Retrieval finds the context; the LLM turns that context plus the question into an answer.$q$),
  ($q$rag-3$q$, $q$What does a document loader do?$q$, $q$["Embeds text into vectors", "Answers questions", "Ranks chunks by relevance", "Reads files such as PDFs, text or web pages into text the pipeline can process"]$q$::jsonb, 3, $q$Loaders are the entry point of ingestion: they turn raw files into documents with text and metadata.$q$),
  ($q$rag-3$q$, $q$Why split documents into chunks before embedding?$q$, $q$["Models have size limits, and smaller pieces give more precise matches", "To encrypt the documents", "Because vector databases only store single words", "To remove stop words"]$q$::jsonb, 0, $q$A focused chunk produces a focused embedding and fits comfortably into the prompt.$q$),
  ($q$rag-3$q$, $q$What is chunk overlap?$q$, $q$["Storing each chunk twice", "Repeating some text from the end of one chunk at the start of the next", "Merging two documents into one", "Overlapping two embeddings"]$q$::jsonb, 1, $q$Overlap keeps a little shared context between neighbouring chunks.$q$),
  ($q$rag-3$q$, $q$Why use chunk overlap?$q$, $q$["To make the database bigger on purpose", "To speed up embedding", "So an idea cut at a chunk boundary still appears whole in at least one chunk", "To avoid needing metadata"]$q$::jsonb, 2, $q$Without overlap, a sentence split across two chunks may not match well in either.$q$),
  ($q$rag-3$q$, $q$Chunks that are too large tend to:$q$, $q$["Always improve answers", "Be impossible to store", "Lose all their metadata", "Mix several topics, so their embedding is less precise"]$q$::jsonb, 3, $q$One vector has to represent everything in the chunk; more topics means a blurrier vector.$q$),
  ($q$rag-3$q$, $q$Chunks that are too small tend to:$q$, $q$["Lose the surrounding context needed to answer", "Always give better answers because they are cheaper", "Break the embedding model", "Ignore the question"]$q$::jsonb, 0, $q$A single sentence may match the query but miss the details around it.$q$),
  ($q$rag-3$q$, $q$What is usually stored alongside each chunk's vector?$q$, $q$["Nothing else", "The chunk text and metadata such as the source file", "A copy of the LLM", "The user's password"]$q$::jsonb, 1, $q$You need the text to put in the prompt and the metadata to cite and filter.$q$),
  ($q$rag-3$q$, $q$In the course, Chroma is:$q$, $q$["An embedding model", "A PDF loader", "An open-source vector database", "A chat interface"]$q$::jsonb, 2, $q$Chroma stores the chunk embeddings and runs the similarity search.$q$),
  ($q$rag-4$q$, $q$What is a LangChain retriever's job?$q$, $q$["Take a query and return relevant documents", "Generate the final answer", "Train the embedding model", "Split text into chunks"]$q$::jsonb, 0, $q$Retrievers are the search component; generation is a separate step.$q$),
  ($q$rag-4$q$, $q$In similarity search, k = 3 means:$q$, $q$["Use 3 embedding models", "Return the 3 most similar chunks", "Split each document into 3 chunks", "Retry the search 3 times"]$q$::jsonb, 1, $q$k is how many top results come back.$q$),
  ($q$rag-4$q$, $q$What does a similarity score threshold do?$q$, $q$["Always returns exactly one chunk", "Sorts results alphabetically", "Only returns chunks whose similarity is above a chosen value", "Removes duplicate documents"]$q$::jsonb, 2, $q$It filters out weak matches instead of always returning a fixed number.$q$),
  ($q$rag-4$q$, $q$What is the risk of setting k very high?$q$, $q$["Retrieval becomes exact", "The embeddings change", "Nothing, more is always better", "Irrelevant chunks get into the prompt, confusing the model and costing more tokens"]$q$::jsonb, 3, $q$Extra low-quality context dilutes the useful part and increases cost.$q$),
  ($q$rag-4$q$, $q$What is the risk of a very strict score threshold?$q$, $q$["Some questions return no chunks at all", "Too many chunks are returned", "Answers get longer", "The database gets corrupted"]$q$::jsonb, 0, $q$If nothing clears the bar, the model has no context to answer from.$q$),
  ($q$rag-4$q$, $q$Before searching, the retriever turns the user's question into:$q$, $q$["A SQL query", "An embedding made with the same model used for the documents", "A list of keywords only", "An image"]$q$::jsonb, 1, $q$The question vector is compared with the stored chunk vectors.$q$),
  ($q$rag-4$q$, $q$Why return chunk metadata with search results?$q$, $q$["It is required to compute similarity", "To make the prompt longer", "So the answer can cite which document it came from", "To train the model"]$q$::jsonb, 2, $q$Metadata like the source file lets users check where an answer came from.$q$),
  ($q$rag-4$q$, $q$Retrieval returns the right chunks, but the answer is still wrong. Where is the problem most likely?$q$, $q$["In the document loader", "In the database's tokenizer", "In cosine similarity", "In the generation step: the prompt or the model"]$q$::jsonb, 3, $q$If the right context arrived, the failure is in how the model was asked to use it.$q$),
  ($q$rag-5$q$, $q$What does cosine similarity measure?$q$, $q$["The exact difference in their lengths", "The angle between two vectors, meaning how aligned they are", "The number of shared words", "How much memory they use"]$q$::jsonb, 1, $q$Cosine looks at direction; vectors pointing the same way are similar.$q$),
  ($q$rag-5$q$, $q$What is the cosine similarity of two vectors pointing in exactly the same direction?$q$, $q$["0", "-1", "1", "Infinity"]$q$::jsonb, 2, $q$cos(0°) = 1, the maximum similarity.$q$),
  ($q$rag-5$q$, $q$What is the cosine similarity of two perpendicular (orthogonal) vectors?$q$, $q$["1", "-1", "0.5", "0"]$q$::jsonb, 3, $q$cos(90°) = 0: the vectors share no direction.$q$),
  ($q$rag-5$q$, $q$Which is the cosine similarity formula?$q$, $q$["dot(A, B) / (|A| x |B|)", "|A| + |B|", "dot(A, B) x |A|", "|A - B| squared"]$q$::jsonb, 0, $q$The dot product divided by both lengths gives the cosine of the angle.$q$),
  ($q$rag-5$q$, $q$If both vectors are normalised to length 1, cosine similarity equals:$q$, $q$["Zero", "Their dot product", "Their sum", "Their Euclidean distance"]$q$::jsonb, 1, $q$With |A| = |B| = 1 the denominator is 1, leaving just the dot product.$q$),
  ($q$rag-5$q$, $q$Why is cosine often preferred over the raw dot product for text embeddings?$q$, $q$["It is always faster to compute", "It works without embeddings", "It ignores vector length and focuses on direction, which carries the meaning", "It always returns whole numbers"]$q$::jsonb, 2, $q$Length can vary with things like text length; direction is the more reliable signal of meaning.$q$),
  ($q$rag-5$q$, $q$What is the range of cosine similarity?$q$, $q$["0 to 100", "0 to infinity", "-100 to 100", "-1 to 1"]$q$::jsonb, 3, $q$It is the cosine of an angle, so it is bounded by -1 and 1.$q$),
  ($q$rag-5$q$, $q$A query scores 0.82 against chunk A and 0.35 against chunk B. Which chunk is more relevant?$q$, $q$["Chunk A", "Chunk B", "They are equally relevant", "Cosine scores can't be compared"]$q$::jsonb, 0, $q$Higher cosine similarity means the vectors point in more similar directions.$q$),
  ($q$rag-6$q$, $q$How do retrieved chunks reach the LLM?$q$, $q$["They are fine-tuned into the model's weights", "They are sent to a separate model", "They are inserted into the prompt as context along with the question", "They are stored in the model's memory permanently"]$q$::jsonb, 2, $q$RAG is prompt construction: context plus question, sent in one request.$q$),
  ($q$rag-6$q$, $q$Which instruction best reduces hallucination in a RAG prompt?$q$, $q$["Be creative and fill any gaps", "Ignore the context if you are unsure", "Always give a long, detailed answer", "Answer only from the provided context, and say you don't know if it isn't there"]$q$::jsonb, 3, $q$Telling the model to stay inside the context and admit gaps keeps answers grounded.$q$),
  ($q$rag-6$q$, $q$Why should a RAG app be allowed to say "I don't know"?$q$, $q$["It is better than inventing an answer the documents don't support", "It saves GPU time", "Vector databases require it", "It makes retrieval faster"]$q$::jsonb, 0, $q$A wrong confident answer does more harm than an honest gap.$q$),
  ($q$rag-6$q$, $q$What is the correct order of a basic RAG request?$q$, $q$["Generate answer, retrieve chunks, embed question, build prompt", "Embed question, retrieve chunks, build prompt, generate answer", "Build prompt, embed documents, train model, answer", "Retrieve chunks, embed question, chunk documents, answer"]$q$::jsonb, 1, $q$Each step needs the output of the previous one.$q$),
  ($q$rag-6$q$, $q$What does it mean to ground an answer?$q$, $q$["Run it on a server", "Make it shorter", "Base it on retrieved source text that can be checked", "Translate it"]$q$::jsonb, 2, $q$Grounded answers can be traced back to specific passages.$q$),
  ($q$rag-6$q$, $q$Putting 20 long chunks into every prompt mainly:$q$, $q$["Always improves accuracy", "Has no effect", "Reduces token usage", "Raises cost and latency and can bury the relevant part"]$q$::jsonb, 3, $q$More context isn't free; the model may also overlook the one passage that matters.$q$),
  ($q$rag-6$q$, $q$Why show sources or citations with answers?$q$, $q$["Users can verify the answer and spot hallucinations", "Embeddings require it", "It makes the model faster", "It reduces chunk size"]$q$::jsonb, 0, $q$Citations make the system checkable and build trust.$q$),
  ($q$rag-6$q$, $q$A user asks something your documents don't cover. What should a good RAG app do?$q$, $q$["Make up a plausible answer", "Say the documents don't cover it", "Return a random chunk", "Crash with an error"]$q$::jsonb, 1, $q$Admitting the gap is the grounded behaviour.$q$),
  ($q$rag-7$q$, $q$In a naive RAG chat, why does the follow-up "What about its price?" fail?$q$, $q$["Prices can't be embedded", "Follow-up questions are too long", "The LLM forgets English", "\"Its\" means nothing on its own, so retrieval searches for the wrong thing"]$q$::jsonb, 3, $q$Without the earlier messages the question has no subject to search for.$q$),
  ($q$rag-7$q$, $q$What does a history-aware retriever do?$q$, $q$["Rewrites the latest question into a standalone question using the chat history, then searches", "Deletes the chat history", "Stores every answer in the vector database", "Ignores the user's question"]$q$::jsonb, 0, $q$The rewritten question carries the missing context into the search.$q$),
  ($q$rag-7$q$, $q$Where is chat history used in conversational RAG?$q$, $q$["Only to train the model", "To reformulate the query and as context when answering", "Nowhere", "Only inside the vector database"]$q$::jsonb, 1, $q$History helps both retrieval (rewriting) and generation (continuity).$q$),
  ($q$rag-7$q$, $q$What is the risk of sending the entire chat history with every request?$q$, $q$["Embeddings become negative", "Retrieval becomes exact", "Cost and context usage grow with every turn", "There is no risk"]$q$::jsonb, 2, $q$Long histories eat context window and tokens; trimming or summarising helps.$q$),
  ($q$rag-7$q$, $q$What is a standalone question?$q$, $q$["A question with one word", "A question asked only once", "A question without punctuation", "One that can be understood without the previous messages"]$q$::jsonb, 3, $q$"What is the Model Y's price?" is standalone; "What about its price?" is not.$q$),
  ($q$rag-7$q$, $q$How is chat history usually stored?$q$, $q$["As a list of user and assistant messages", "As a single embedding", "As a PDF", "Inside the vector index"]$q$::jsonb, 0, $q$Message lists are what chat models take as input.$q$),
  ($q$rag-7$q$, $q$Why not embed the whole conversation as the search query?$q$, $q$["It isn't allowed", "Older topics in the history dilute the search for the current question", "Embeddings can't contain questions", "It would always be better"]$q$::jsonb, 1, $q$A focused standalone question retrieves better than a mix of everything said so far.$q$),
  ($q$rag-7$q$, $q$Which component usually rewrites the follow-up question?$q$, $q$["The vector database", "The text splitter", "An LLM call with a rewrite prompt", "The document loader"]$q$::jsonb, 2, $q$Rewriting needs language understanding, so it is an LLM step.$q$),
  ($q$rag-8$q$, $q$How does fixed-size chunking split text?$q$, $q$["By a set number of characters or tokens", "By meaning", "By headings only", "At random points"]$q$::jsonb, 0, $q$It is the simplest strategy: cut every N characters or tokens.$q$),
  ($q$rag-8$q$, $q$What is the main weakness of fixed-size chunking?$q$, $q$["It is too slow", "It can cut sentences or ideas in half", "Its chunks can't be embedded", "It needs an LLM"]$q$::jsonb, 1, $q$Cuts ignore the structure of the text.$q$),
  ($q$rag-8$q$, $q$What does recursive splitting try to do?$q$, $q$["Split at random", "Merge documents together", "Split on natural boundaries (paragraphs, then lines, then sentences) and go smaller only when needed", "Remove punctuation"]$q$::jsonb, 2, $q$It respects structure first and only falls back to finer cuts for oversized pieces.$q$),
  ($q$rag-8$q$, $q$Semantic chunking decides chunk boundaries using:$q$, $q$["File size", "The number of images", "Alphabetical order", "Changes in meaning measured with embeddings"]$q$::jsonb, 3, $q$When neighbouring sentences drift apart in meaning, a new chunk starts.$q$),
  ($q$rag-8$q$, $q$What is the typical trade-off of larger chunks?$q$, $q$["More context per chunk but less precise retrieval", "They are always better", "They are always worse", "Chunk size has no effect"]$q$::jsonb, 0, $q$Big chunks carry more context but their embeddings are less specific.$q$),
  ($q$rag-8$q$, $q$What does an overlap of about 10-20% usually give you?$q$, $q$["Double the storage", "Context kept across boundaries at a small storage cost", "Broken retrieval", "Fewer duplicates"]$q$::jsonb, 1, $q$A modest overlap protects boundary sentences without bloating the index much.$q$),
  ($q$rag-8$q$, $q$For an FAQ where each question and answer is self-contained, what is the best chunk?$q$, $q$["Every 50 characters", "The whole document as one chunk", "One question with its answer", "Every single word"]$q$::jsonb, 2, $q$Matching the chunk to the natural unit of meaning gives the cleanest retrieval.$q$),
  ($q$rag-8$q$, $q$Why test chunking settings with real questions?$q$, $q$["Chunking has no effect on results", "LangChain requires it", "To train the embedding model", "The best settings depend on your documents and your queries"]$q$::jsonb, 3, $q$There is no universal best chunk size; measure on your own data.$q$),
  ($q$rag-9$q$, $q$In what order does RecursiveCharacterTextSplitter try separators by default?$q$, $q$["Single characters first, then words", "Paragraph breaks, then line breaks, then spaces, then single characters", "Sentences found by regex only", "Headings, then tables, then images"]$q$::jsonb, 1, $q$The defaults are "\n\n", "\n", " " and "": coarse to fine.$q$),
  ($q$rag-9$q$, $q$Why split by tokens instead of characters?$q$, $q$["Tokens are always whole words", "Characters can't be embedded", "Model limits and costs are measured in tokens", "PDFs require it"]$q$::jsonb, 2, $q$Token-based sizes map directly onto context windows and pricing.$q$),
  ($q$rag-9$q$, $q$What can a Markdown header splitter do?$q$, $q$["Translate the Markdown", "Remove all code blocks", "Render it as HTML", "Split on headings and keep the heading as metadata"]$q$::jsonb, 3, $q$Headings become context for each chunk, which helps retrieval and citations.$q$),
  ($q$rag-9$q$, $q$Why use a language-aware splitter for source code?$q$, $q$["It splits on functions and classes instead of in the middle of a statement", "It runs the code", "It removes comments", "It compresses the code"]$q$::jsonb, 0, $q$Code has its own structure; respecting it keeps chunks meaningful.$q$),
  ($q$rag-9$q$, $q$What does chunk_size=500, chunk_overlap=50 mean?$q$, $q$["500 chunks of 50 words each", "Chunks of up to about 500 units, with 50 shared between neighbours", "50 chunks of 500 words each", "An overlap of 500 units"]$q$::jsonb, 1, $q$Size is the maximum per chunk; overlap is how much repeats between neighbours.$q$),
  ($q$rag-9$q$, $q$Why might a splitter produce a chunk smaller than chunk_size?$q$, $q$["It's a bug", "The overlap was negative", "It stopped at a natural separator rather than cutting mid-text", "The embeddings shrank"]$q$::jsonb, 2, $q$chunk_size is a maximum, not an exact target.$q$),
  ($q$rag-9$q$, $q$What goes wrong if a table is split row by row without its header?$q$, $q$["Nothing, it's perfect", "Embeddings get faster", "The table gets more accurate", "The chunks lose the column names needed to understand them"]$q$::jsonb, 3, $q$A row of numbers without headers has no meaning on its own.$q$),
  ($q$rag-9$q$, $q$What does length_function control in a text splitter?$q$, $q$["How chunk size is measured, for example characters or tokens", "How many chunks are returned", "The embedding dimension", "The LLM's temperature"]$q$::jsonb, 0, $q$Swap in a token counter to make chunk_size mean tokens.$q$),
  ($q$rag-10$q$, $q$When does a semantic chunker start a new chunk?$q$, $q$["After a fixed number of characters", "Whenever a heading appears", "When the embedding distance between consecutive sentences jumps above a threshold", "At random"]$q$::jsonb, 2, $q$A large jump in distance signals a change of topic.$q$),
  ($q$rag-10$q$, $q$A percentile breakpoint threshold of 95 means:$q$, $q$["Make 95 chunks", "Use 95% overlap", "Cut every 95 characters", "Split only at the largest 5% of distance jumps"]$q$::jsonb, 3, $q$Only the biggest topic shifts become chunk boundaries.$q$),
  ($q$rag-10$q$, $q$What extra cost does semantic chunking have compared with recursive splitting?$q$, $q$["Every sentence has to be embedded during ingestion", "It needs GPUs at query time", "Answers get longer", "There is no extra cost"]$q$::jsonb, 0, $q$It needs embeddings just to decide where to cut.$q$),
  ($q$rag-10$q$, $q$When is semantic chunking most useful?$q$, $q$["For short tweets", "For long text that drifts between topics without clear headings", "For tables", "For source code"]$q$::jsonb, 1, $q$Without structural markers, meaning is the best guide to boundaries.$q$),
  ($q$rag-10$q$, $q$What is a downside of semantic chunking?$q$, $q$["Its chunks can't be stored", "It always needs internet access", "Chunk sizes can vary a lot, some very large or very small", "It breaks cosine similarity"]$q$::jsonb, 2, $q$Boundaries follow meaning, not size, so sizes are uneven.$q$),
  ($q$rag-10$q$, $q$What does a semantic chunker compare?$q$, $q$["Each sentence with the user's query", "Whole documents with each other", "Words with letters", "Neighbouring sentences (or small groups of sentences) with each other"]$q$::jsonb, 3, $q$It measures how much meaning shifts from one sentence to the next.$q$),
  ($q$rag-10$q$, $q$Lowering the breakpoint threshold generally gives:$q$, $q$["More, smaller chunks", "Fewer, larger chunks", "Exactly the same chunks", "No chunks at all"]$q$::jsonb, 0, $q$A lower bar means more distance jumps count as boundaries.$q$),
  ($q$rag-10$q$, $q$Does semantic chunking change how retrieval works at query time?$q$, $q$["Yes, it needs a new kind of database", "No, it only changes how documents are split during ingestion", "Yes, it calls an LLM for every query", "Yes, it doubles query cost"]$q$::jsonb, 1, $q$The resulting chunks are embedded and searched like any others.$q$),
  ($q$rag-11$q$, $q$What does agentic chunking use to decide chunk boundaries?$q$, $q$["Regular expressions", "A fixed size", "Cosine similarity only", "An LLM that reads the text"]$q$::jsonb, 3, $q$The model groups text into chunks based on its understanding of the content.$q$),
  ($q$rag-11$q$, $q$In agentic chunking, what is a proposition?$q$, $q$["A short, self-contained statement of a single fact", "A full paragraph", "A heading", "An embedding vector"]$q$::jsonb, 0, $q$Propositions are small, atomic facts that make sense on their own.$q$),
  ($q$rag-11$q$, $q$What is the main cost of agentic chunking?$q$, $q$["There is no extra cost", "LLM calls over all the text during ingestion, which is slower and more expensive", "Smaller vectors", "Faster queries"]$q$::jsonb, 1, $q$Every document passes through a model before it is indexed.$q$),
  ($q$rag-11$q$, $q$Why rewrite "He founded it in 2002" as "Elon Musk founded SpaceX in 2002"?$q$, $q$["To make it shorter", "Because Chroma requires it", "So the chunk makes sense on its own when retrieved", "To remove the names"]$q$::jsonb, 2, $q$Retrieved chunks arrive without their neighbours, so pronouns must be resolved.$q$),
  ($q$rag-11$q$, $q$When is agentic chunking worth the cost?$q$, $q$["For every tweet", "For real-time log streams", "Never", "For high-value documents where retrieval quality matters more than ingestion cost"]$q$::jsonb, 3, $q$Pay the extra cost once where answer quality really matters.$q$),
  ($q$rag-11$q$, $q$What is a risk of agentic chunking?$q$, $q$["The LLM may drop or change facts while rewriting", "Its chunks can't be embedded", "It is fully deterministic", "Its chunks are too small to store"]$q$::jsonb, 0, $q$Any rewriting step can introduce errors; spot-check the output.$q$),
  ($q$rag-11$q$, $q$When does agentic chunking run?$q$, $q$["On every user question", "During ingestion, once per document", "Only while training the model", "Never"]$q$::jsonb, 1, $q$Like other chunking, it is part of preparing the index.$q$),
  ($q$rag-11$q$, $q$How does agentic chunking differ from semantic chunking?$q$, $q$["They are identical", "It uses no model at all", "It relies on an LLM's understanding instead of embedding distances", "It only works on code"]$q$::jsonb, 2, $q$Semantic chunking measures distances; agentic chunking asks a model to decide.$q$),
  ($q$rag-12$q$, $q$What is the problem with images in PDFs for a text-only RAG pipeline?$q$, $q$["Information in charts and images is lost if you only extract the text", "Images are encrypted", "Text can't be extracted from PDFs", "There is no problem"]$q$::jsonb, 0, $q$A chart's numbers never reach the index unless you handle the image.$q$),
  ($q$rag-12$q$, $q$What is a common way to make images searchable?$q$, $q$["Delete the images", "Generate text summaries of the images with a vision model and embed the summaries", "Embed the image file size", "Only index the PDF title"]$q$::jsonb, 1, $q$Summaries turn visual content into text the retriever can match.$q$),
  ($q$rag-12$q$, $q$How does the unstructured library help?$q$, $q$["It trains models", "It hosts the vector database", "It partitions documents into elements such as titles, text, tables and images", "It provides a chat interface"]$q$::jsonb, 2, $q$Knowing each element's type lets you treat tables and images differently.$q$),
  ($q$rag-12$q$, $q$Why keep a link from an image summary back to the original image?$q$, $q$["Cosine similarity needs it", "It reduces cost", "There is no reason", "So the answer step can show the real image or pass it to a vision model"]$q$::jsonb, 3, $q$The summary is for search; the image itself may be needed to answer.$q$),
  ($q$rag-12$q$, $q$How should tables usually be handled?$q$, $q$["Kept intact, for example as HTML or Markdown, rather than split mid-table", "Split into single cells", "Removed", "Converted into images"]$q$::jsonb, 0, $q$A table only makes sense with its rows and headers together.$q$),
  ($q$rag-12$q$, $q$What can a multimodal embedding model do?$q$, $q$["Embed only text", "Put images and text in the same vector space, so text queries can match images", "Embed only audio", "Compress PDFs"]$q$::jsonb, 1, $q$A shared space makes cross-modal search possible.$q$),
  ($q$rag-12$q$, $q$What extra cost does multimodal RAG usually add?$q$, $q$["Nothing", "A smaller database", "Vision-model calls during ingestion to describe images", "Faster answers"]$q$::jsonb, 2, $q$Each image needs processing before it can be indexed.$q$),
  ($q$rag-12$q$, $q$What does a scanned, image-only PDF need first?$q$, $q$["Nothing", "Cosine similarity", "Bigger chunks", "OCR to extract the text"]$q$::jsonb, 3, $q$Without OCR there is no text to chunk or embed.$q$),
  ($q$rag-13$q$, $q$What does Maximal Marginal Relevance (MMR) aim for?$q$, $q$["Only the single most similar results", "Results that are relevant but also different from each other", "Random results", "The shortest chunks"]$q$::jsonb, 1, $q$MMR balances relevance against redundancy.$q$),
  ($q$rag-13$q$, $q$Why does diversity in results matter?$q$, $q$["It doesn't matter", "To use more tokens on purpose", "The top results can be near-duplicates that waste context", "Cosine similarity requires it"]$q$::jsonb, 2, $q$Three copies of the same paragraph add no new information.$q$),
  ($q$rag-13$q$, $q$In MMR, lambda_mult = 1 means:$q$, $q$["Pure diversity", "Random selection", "No results", "Pure relevance, with no diversity"]$q$::jsonb, 3, $q$Lower values push harder toward diverse results.$q$),
  ($q$rag-13$q$, $q$What does metadata filtering do?$q$, $q$["Restricts the search to chunks whose metadata matches, for example source = \"Tesla\"", "Changes the embeddings", "Deletes the metadata", "Sorts results alphabetically"]$q$::jsonb, 0, $q$Filters apply hard conditions before or alongside similarity search.$q$),
  ($q$rag-13$q$, $q$For "What did Nvidia's report say about revenue?", what is the best use of metadata?$q$, $q$["Ignore metadata", "Filter to chunks from the Nvidia document before the similarity search", "Filter by chunk length", "Pick a random document"]$q$::jsonb, 1, $q$This keeps other companies' revenue sections out of the results.$q$),
  ($q$rag-13$q$, $q$In MMR, what is fetch_k?$q$, $q$["The final number of results", "The embedding dimension", "How many candidates are fetched before MMR picks the final k", "The chunk overlap"]$q$::jsonb, 2, $q$MMR needs a larger pool to choose a diverse subset from.$q$),
  ($q$rag-13$q$, $q$What does score-threshold retrieval return?$q$, $q$["Always exactly k chunks", "Exactly one chunk", "Random chunks", "All chunks above a similarity cutoff, possibly none"]$q$::jsonb, 3, $q$The number of results depends on how many clear the bar.$q$),
  ($q$rag-13$q$, $q$Why combine metadata filters with similarity search?$q$, $q$["Filters enforce hard rules while similarity ranks by meaning", "They do the same thing", "Filters are always slower", "Similarity can't rank results"]$q$::jsonb, 0, $q$Together they give results that are both allowed and relevant.$q$),
  ($q$rag-14$q$, $q$What is multi-query retrieval?$q$, $q$["Asking the user to rephrase", "Querying several databases with the same text", "Using an LLM to write several versions of the question and retrieving for each", "Repeating the same query"]$q$::jsonb, 2, $q$Different phrasings reach different parts of the vector space.$q$),
  ($q$rag-14$q$, $q$Why does multi-query retrieval help?$q$, $q$["It is faster", "It uses fewer tokens", "It only improves precision", "One phrasing can miss chunks that another phrasing finds, so recall improves"]$q$::jsonb, 3, $q$Covering more phrasings means fewer relevant chunks are missed.$q$),
  ($q$rag-14$q$, $q$After retrieving for each variation, what happens to the results?$q$, $q$["They are merged and de-duplicated", "All but the first list are discarded", "They are averaged into one vector", "They are sorted alphabetically"]$q$::jsonb, 0, $q$The union of all lists, without repeats, goes forward.$q$),
  ($q$rag-14$q$, $q$What is the main cost of multi-query retrieval?$q$, $q$["There is no cost", "An extra LLM call plus several searches per question", "Bigger embeddings", "Retraining the model"]$q$::jsonb, 1, $q$You pay for generating the variations and running each search.$q$),
  ($q$rag-14$q$, $q$What does recall mean in retrieval?$q$, $q$["How fast retrieval is", "How much memory it uses", "The share of relevant chunks that you actually retrieved", "The share of retrieved chunks that are relevant"]$q$::jsonb, 2, $q$The last option describes precision; recall is about not missing relevant chunks.$q$),
  ($q$rag-14$q$, $q$When is multi-query retrieval a good fit?$q$, $q$["Exact ID lookups", "Single-keyword searches", "When there are no documents", "For vague or short questions that could be phrased many ways"]$q$::jsonb, 3, $q$Ambiguous questions benefit most from multiple phrasings.$q$),
  ($q$rag-14$q$, $q$Multi-query can be combined with reciprocal rank fusion to:$q$, $q$["Rank the merged results by how high they appear across the lists", "Only delete duplicates", "Change the embeddings", "Do nothing useful"]$q$::jsonb, 0, $q$Chunks that rank well for several phrasings rise to the top.$q$),
  ($q$rag-14$q$, $q$What is a risk of multi-query retrieval?$q$, $q$["There is no risk", "Generated variations can drift from the user's intent and pull in off-topic chunks", "Recall goes down", "Results can't be merged"]$q$::jsonb, 1, $q$A bad rewrite searches for something the user didn't ask.$q$),
  ($q$rag-15$q$, $q$What does reciprocal rank fusion (RRF) combine?$q$, $q$["Several embeddings into one", "Several chunks into one", "Several models into one", "Several ranked result lists into one ranking"]$q$::jsonb, 3, $q$It fuses rankings from different searches or retrievers.$q$),
  ($q$rag-15$q$, $q$What is the RRF score of a document?$q$, $q$["The sum over all lists of 1 / (k + rank)", "rank x k", "cosine similarity x rank", "Its highest rank"]$q$::jsonb, 0, $q$Each list contributes more when the document ranks higher in it.$q$),
  ($q$rag-15$q$, $q$Why does RRF use ranks instead of raw scores?$q$, $q$["Ranks are faster to compute", "Scores from different retrievers (like BM25 and cosine) aren't on the same scale", "Scores are kept secret", "There is no reason"]$q$::jsonb, 1, $q$Ranks are comparable across retrievers; raw scores are not.$q$),
  ($q$rag-15$q$, $q$Document X is ranked 1st in two lists; document Y is 1st in only one. After RRF:$q$, $q$["They get the same score", "Y gets the higher score", "X gets the higher fused score", "It can't be determined"]$q$::jsonb, 2, $q$X collects a contribution from both lists.$q$),
  ($q$rag-15$q$, $q$What is a common value for the constant k in RRF?$q$, $q$["1", "1000", "0", "60"]$q$::jsonb, 3, $q$k = 60 comes from the original RRF paper and is a widely used default.$q$),
  ($q$rag-15$q$, $q$What does a larger k do in RRF?$q$, $q$["Shrinks the gap between top ranks, so lower-ranked items matter relatively more", "Nothing", "Removes documents", "Reverses the ranking"]$q$::jsonb, 0, $q$With a large k, 1/(k+1) and 1/(k+10) are closer together.$q$),
  ($q$rag-15$q$, $q$A document appears in only one list, at rank 50, with k = 60. What does it contribute?$q$, $q$["50/60", "1/110", "60/50", "110"]$q$::jsonb, 1, $q$1 / (60 + 50) = 1/110.$q$),
  ($q$rag-15$q$, $q$Where is RRF typically used?$q$, $q$["Chunking documents", "Creating embeddings", "Fusing results from multi-query or hybrid (keyword plus vector) search", "Generating answers"]$q$::jsonb, 2, $q$Whenever several ranked lists need to become one, RRF is a simple choice.$q$),
  ($q$rag-16$q$, $q$What is BM25?$q$, $q$["A keyword-based ranking function", "An embedding model", "A vector database", "A large language model"]$q$::jsonb, 0, $q$BM25 scores documents by term frequency and rarity, without embeddings.$q$),
  ($q$rag-16$q$, $q$When does keyword search beat vector search?$q$, $q$["When the query uses synonyms", "When exact terms matter, like product codes, names or error codes", "When the query is a paraphrase", "Never"]$q$::jsonb, 1, $q$Embeddings can blur exact strings; keyword search matches them precisely.$q$),
  ($q$rag-16$q$, $q$When does vector search beat keyword search?$q$, $q$["Exact ID lookups", "When there are no documents", "When the query uses different words with the same meaning", "Never"]$q$::jsonb, 2, $q$Semantic matching finds paraphrases that share no keywords.$q$),
  ($q$rag-16$q$, $q$What is hybrid search?$q$, $q$["Vector search only", "Keyword search run twice", "Letting the LLM pick documents", "Running keyword and vector search and combining the results"]$q$::jsonb, 3, $q$It gets the strengths of both approaches.$q$),
  ($q$rag-16$q$, $q$How do dense and sparse retrieval differ?$q$, $q$["Dense uses embeddings with mostly non-zero values; sparse uses keyword vectors that are mostly zeros", "Dense is keyword-based and sparse uses embeddings", "They are the same thing", "Dense vectors are always shorter"]$q$::jsonb, 0, $q$Sparse vectors have one slot per vocabulary term, nearly all empty.$q$),
  ($q$rag-16$q$, $q$What do the weights in an EnsembleRetriever control?$q$, $q$["The embedding dimension", "How much each retriever contributes to the final ranking", "The chunk size", "The LLM's temperature"]$q$::jsonb, 1, $q$For example 0.5/0.5 treats keyword and vector search equally.$q$),
  ($q$rag-16$q$, $q$For the query "error E1042 in pump", why lean more on keyword search?$q$, $q$["Codes embed especially well", "The query is short", "The exact code E1042 matters more than general meaning", "No particular reason"]$q$::jsonb, 2, $q$Keyword search reliably matches the exact code.$q$),
  ($q$rag-16$q$, $q$What does BM25 need that vector search doesn't?$q$, $q$["A GPU", "An LLM", "Images", "Term statistics over the documents, such as word frequencies"]$q$::jsonb, 3, $q$BM25 scores depend on how often terms appear in each document and across the collection.$q$),
  ($q$rag-17$q$, $q$What does a reranker do?$q$, $q$["Replaces the vector database", "Re-scores a small set of retrieved candidates more accurately and reorders them", "Splits documents into chunks", "Writes the final answer"]$q$::jsonb, 1, $q$Reranking is a precision step on top of a first-stage search.$q$),
  ($q$rag-17$q$, $q$What is two-stage retrieval?$q$, $q$["Using two vector databases", "Using two LLMs to answer", "A fast, broad search for many candidates, then a slower, precise rerank of those", "Retrying a failed search"]$q$::jsonb, 2, $q$Stage one is cheap and wide; stage two is accurate and narrow.$q$),
  ($q$rag-17$q$, $q$How does a cross-encoder differ from a bi-encoder?$q$, $q$["They are the same", "A cross-encoder is always faster", "A bi-encoder reads query and document together", "A cross-encoder reads the query and document together; a bi-encoder embeds them separately"]$q$::jsonb, 3, $q$Reading them together lets the model judge relevance more precisely.$q$),
  ($q$rag-17$q$, $q$Why not run a cross-encoder over every document?$q$, $q$["It is too slow and costly, since it runs once per query-document pair", "It is less accurate", "It can't process text", "It is free, so there is no reason not to"]$q$::jsonb, 0, $q$That's why it's only applied to a short candidate list.$q$),
  ($q$rag-17$q$, $q$What is a typical reranking setup?$q$, $q$["Retrieve 1 and rerank it", "Retrieve the top 20-50, rerank them, keep the top 3-5 for the prompt", "Rerank every document in the database", "Skip retrieval entirely"]$q$::jsonb, 1, $q$Wide first, then narrow to what the model actually needs.$q$),
  ($q$rag-17$q$, $q$What is Cohere Rerank?$q$, $q$["A vector store", "A text splitter", "A hosted reranking API", "A chat model"]$q$::jsonb, 2, $q$You send a query and candidate texts; it returns relevance scores.$q$),
  ($q$rag-17$q$, $q$What does reranking mainly improve?$q$, $q$["Ingestion speed", "Storage size", "The recall of the first-stage search", "The precision of the final chunks sent to the LLM"]$q$::jsonb, 3, $q$It can only reorder what stage one found, so it sharpens precision.$q$),
  ($q$rag-17$q$, $q$What is the trade-off of adding a reranker?$q$, $q$["Extra latency and cost on every query", "There is none", "Lower accuracy", "Bigger chunks"]$q$::jsonb, 0, $q$Each question needs an additional model call.$q$);
